patientdb/patient/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from django.conf import settings
from patient.views import ( index, ClientView, 
                        ClientDetailView, 
                        ClientCreate, 
                        ClientDelete, 
                        ClientUpdate, 
                        SearchList, 
                        ServiceView, 
                        ServiceDetailView, 
                        ServiceCreate, 
                        ServiceUpdate, 
                        ServiceDelete,
                        PrintPdf, 
                        CardiologistCreate, 
                        CardiologistView, 
                        CardiologistDetailView, 
                        CardiologistDelete, 
                        CardiologistUpdate, 
                        CardiologistSearchList,
                        GeneralPractitionerCreate, 
                        GeneralPractitionerView, 
                        GeneralPractitionerDetailView, 
                        GeneralPractitionerDelete, 
                        GeneralPractitionerUpdate, 
                        GeneralPractitionerSearchList
                         )
                   
# App name to use                      
app_name = 'client'

# URL patterns 

urlpatterns = [
    path('client/', ClientView.as_view(), name='client_index'),
    path('', index, name='index'),
    #path('<int:pk>/detail/', ClientDetailView.as_view(), name='detail'),

    # /clients/add-delete-update-search
    path('client/new/', ClientCreate.as_view(), name='client_new'),
    path('client/<int:pk>/delete', ClientDelete.as_view(), name='client_delete'),
    path('client/<int:pk>/update', ClientUpdate.as_view(), name='client_update'),
    path('client/<int:pk>/details', ClientDetailView.as_view(), name='client_detail'),
    path('client/search', SearchList.as_view(), name='search'),
    #/services
    path('client/<int:pk>/history', ServiceView.as_view(), name='history'),
    path('client/<int:client.pk>/service/<int:pk>/detail', ServiceDetailView.as_view(), name='service_detail'),
    path('client/<int:client.pk>/service/<int:pk>/detail/pdf_html/', PrintPdf.as_view(), name='service_html_pdf'),
    #path('client/service/add', ServiceCreate.as_view(), name='service_add'),
    path('client/<int:pk>/service/add', ServiceCreate.as_view(), name='service_new'),
    path('client/<int:client.pk>/service/<int:pk>/update', ServiceUpdate.as_view(), name='service_update'),
    path('client/<int:pk>/service/<int:service.pk>/delete', ServiceDelete.as_view(), name='service_delete'),


    # /doctors
    #path('cardiologist/new/',CardiologistCreate.as_view() , name='cardiologist_new'),
    #path('cardiologist/index', CardiologistView.as_view(), name='cardiologist_index'),
    #path('cardiologist/<int:pk>/cardiologist_detail/', CardiologistDetailView.as_view(), name='cardiologist_detail'),
    #path('cardiologist/<int:pk>/delete', CardiologistDelete.as_view(), name='cardiologist_delete'),
    #path('cardiologist/<int:pk>/update', CardiologistUpdate.as_view(), name='cardiologist_update'),
    #path('cardiologist/search', CardiologistSearchList.as_view(), name='cardiologist_search'),


    #path('gp/new/',GeneralPractitionerCreate.as_view() , name='generalpractitioner_new'),
    #path('gp/index', GeneralPractitionerView.as_view(), name='generalpractitioner_index'),
    #path('gp/<int:pk>/details/', GeneralPractitionerDetailView.as_view(), name='generalpractitioner_detail'),
    #path('gp/<int:pk>/delete', GeneralPractitionerDelete.as_view(), name='generalpractitioner_delete'),
    #path('gp/<int:pk>/update', GeneralPractitionerUpdate.as_view(), name='generalpactitioner_update'),
    #path('gp/search', GeneralPractitionerSearchList.as_view(), name='generalpractitioner_search'),

]

patientdb/patient/forms.py
from django import forms
from .models import Client, Service, Cardiologist, General_Practitioner
from bootstrap_datepicker_plus import DateTimePickerInput
#from bootstrap_modal_forms.forms import BSModalForm
#from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


    
class ClientForm(forms.ModelForm):
    
    #cardiologist = forms.ModelChoiceField(queryset=Cardiologist.objects.all().order_by('last_name'), to_field_name="last_name")

    class Meta:
        model = Client
        fields= [
                    'record_number',
                    'first_name', 
                    'last_name',
                    'dob', 
                    'device', 
                    'implant_date', 
                    'device_serial', 
                    'cardiologist',
                    'general_practitioner',
                    ]
        widgets = {
            'dob': forms.DateInput(attrs={'class': 'datepicker', 'type':'date'}),
            'implant_date': forms.DateInput(attrs={'class': 'datepicker', 'type':'date'})
            }
    

class ServiceForm(forms.ModelForm):

   class Meta:
        model = Service
        fields = [
                    'client',
                    'MDC_IDC_SESS_TYPE',
                    'MDC_IDC_SESS_DTM',
                    'MDC_IDC_MSMT_BATTERY_VOLTAGE',
                    'MDC_IDC_MSMT_CAP_CHARGE_TIME',
                    'MDC_IDC_STAT_BRADY_RA_PERCENT_PACED',
                    'MDC_IDC_STAT_BRADY_RV_PERCENT_PACED',
                    'MDC_IDC_STAT_CRT_LV_PERCENT_PACED',
                    'MDC_IDC_MSMT_LEADCHNL_RA_SENSING_INTR_AMPL_MEAN',
                    'MDC_IDC_MSMT_LEADCHNL_RA_IMPEDANCE_VALUE',
                    'MDC_IDC_MSMT_LEADCHNL_RA_PACING_THRESHOLD_AMPLITUDE',
                    'MDC_IDC_MSMT_LEADCHNL_RA_PACING_THRESHOLD_PULSEWIDTH',
                    'MDC_IDC_MSMT_LEADCHNL_RV_SENSING_INTR_AMPL_MEAN',
                    'MDC_IDC_MSMT_LEADCHNL_RV_IMPEDANCE_VALUE',
                    'MDC_IDC_MSMT_LEADCHNL_RV_PACING_THRESHOLD_AMPLITUDE',
                    'MDC_IDC_MSMT_LEADCHNL_RV_PACING_THRESHOLD_PULSEWIDTH',
                    'MDC_IDC_MSMT_LEADHVCHNL_IMPEDANCE',
                    'MDC_IDC_SESS_COMMENTS',
                    ]
        labels = {
            'MDC_IDC_SESS_TYPE': 'Service Type',
            'MDC_IDC_SESS_DTM': 'Service Date',
            'MDC_IDC_MSMT_BATTERY_VOLTAGE': 'Battery Voltage',
            'MDC_IDC_MSMT_CAP_CHARGE_TIME': 'Battery Charge Time',
            'MDC_IDC_STAT_BRADY_RA_PERCENT_PACED': 'RA Pacing Percentage',
            'MDC_IDC_STAT_BRADY_RV_PERCENT_PACED': 'RV Pacing Percentage',
            'MDC_IDC_STAT_CRT_LV_PERCENT_PACED': 'LV Pacing Percentage',
            'MDC_IDC_MSMT_LEADCHNL_RA_SENSING_INTR_AMPL_MEAN':'RA Sensing Amplitude',
            'MDC_IDC_MSMT_LEADCHNL_RA_IMPEDANCE_VALUE':'RA Pacing Impedance',
            'MDC_IDC_MSMT_LEADCHNL_RA_PACING_THRESHOLD_AMPLITUDE':'RA Pacing Theshold',
            'MDC_IDC_MSMT_LEADCHNL_RA_PACING_THRESHOLD_PULSEWIDTH':'RA Pacing Pulse Width',
            'MDC_IDC_MSMT_LEADCHNL_RV_SENSING_INTR_AMPL_MEAN':'RV Sensing Amplitude',
            'MDC_IDC_MSMT_LEADCHNL_RV_IMPEDANCE_VALUE':'RV Pacing Impedance',
            'MDC_IDC_MSMT_LEADCHNL_RV_PACING_THRESHOLD_AMPLITUDE':'RV Pacing Theshold',
            'MDC_IDC_MSMT_LEADCHNL_RV_PACING_THRESHOLD_PULSEWIDTH':'RV Pacing Pulse Width',
            'MDC_IDC_MSMT_LEADHVCHNL_IMPEDANCE':'RV Shock Pacing Impedance',
            'MDC_IDC_SESS_COMMENTS': 'Comments',
            }
        widgets = {
            'client': forms.HiddenInput(),
            'MDC_IDC_SESS_DTM': DateTimePickerInput(attrs={'class': 'dateicker', 'type':'datetime'})  
            }
        

class SearchForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('last_name',)


class CardiologistForm(forms.ModelForm):
    class Meta: 
        model = Cardiologist
        fields = ('first_name','last_name','str_address','ct_address','pc_address','st_address','phone_1','phone_2', 'email')
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'str_address': 'Street',
            'ct_address': 'City',
            'pc_address':'Post Code',
            'st_address': 'State',
            'phone_1': 'Phone 1',
            'phone_2': 'Phone 2',
            'email': 'Email'
            }


class General_PractitionerForm(forms.ModelForm):
    class Meta: 
        model = General_Practitioner
        fields = ('first_name','last_name','str_address','ct_address','pc_address','st_address','phone_1','phone_2', 'email')
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'str_address': 'Street',
            'ct_address': 'City',
            'pc_address':'Post Code',
            'st_address': 'State',
            'phone_1': 'Phone 1',
            'phone_2': 'Phone 2',
            'email': 'Email'
            }

patientdb/patient/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from .models import Client, Service, Cardiologist, General_Practitioner, Device
from django.http import HttpResponse
#from .utils import render_to_pdf
from django.shortcuts import redirect
from .forms import SearchForm, ClientForm, CardiologistForm, General_PractitionerForm, ServiceForm
from django.contrib import messages
from django.urls import	reverse_lazy, reverse
from django.db.models import Q
from django.utils import timezone
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django_weasyprint import WeasyTemplateResponseMixin, WeasyTemplateView

from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.template import Context
from django.template.loader import render_to_string
from weasyprint import HTML, CSS

from itertools import chain

# Main page
def index(request):
    return render(request, 'clients/index.html')


# Clients
class ClientView(ListView):
    template_name = 'clients/client_index.html'
    context_object_name = 'all_clients'
    paginate_by = 10

    def get_queryset(self):
        return Client.objects.all()


class ClientDetailView(DetailView, DeleteView, CreateView):
    model = Client
    template_name = 'clients/client_detail.html'
    success_url = reverse_lazy('client:index')
    form_class = ClientForm


class ClientCreate(CreateView):
   model = Client
   template_name = 'clients/client_new.html'
   form_class = ClientForm

class ClientUpdate(UpdateView):
    model = Client
    form_class = ClientForm
    template_name_suffix = '_update_form'

class ClientDelete(DeleteView):
    model = Client
    success_url = reverse_lazy('client:index')


class SearchList(ListView):
    template_name = 'clients/client_index.html'
    model = Client
    context_object_name = 'all_clients'

    def get_queryset(self):
        search = self.request.GET.get('search')
        queryset = Client.objects.filter(Q(last_name__icontains=search)|Q(first_name__icontains=search)|Q(record_number__icontains=search))
        return queryset


# Services
# search services from ServiceListView
class ServiceSearchList():
    template_name = ''
    model = Service
    context_object_name = ''

    def get_queryset(self):
        pass


class ServiceCreate(CreateView):
    template_name = 'clients/oos/service_new.html'
    form_class = ServiceForm

    def get_initial(self, **kwargs):
        initial = super(ServiceCreate, self).get_initial()
        initial['client'] = self.kwargs.get('pk')
        return initial



class ServiceView(SingleObjectMixin, ListView):
    template_name = 'clients/oos/service_history.html'
    context_object_name = 'all_services'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Client.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        # Create any data and add it to the context
        context['client'] = self.object
        return context

    def get_queryset(self):
        queryset = self.object.service_set.all()
        #queryset2 = self.object.procedure_set.all()
        #queryset = list (chain(queryset1, queryset2))
        return queryset


class ServiceDetailView(DetailView, DeleteView, CreateView):
    model = Service
    template_name = 'clients/oos/service_detail.html'
    success_url = reverse_lazy('client:service_detail')
    form_class = ServiceForm
    def get_queryset(self, *args, **kwargs):
        queryset = Service.objects.filter(id=self.kwargs.get('pk')).prefetch_related('client')
        return queryset


#class ServiceCreate(CreateView):
#    template_name = 'clients/service/service_new.html'
#    model = Service
#    form_class = ServiceForm


class ServiceUpdate(UpdateView):
    model = Service
    form_class = ServiceForm
    #template_name_suffix = '_update_form'
    template_name = 'clients/oos/service_update.html'
    success_url = reverse_lazy('client:service_detail')

    def get_initial(self, **kwargs):
        initial = super(ServiceUpdate, self).get_initial()
        initial['client'] = self.kwargs.get('client_id')
        return initial


class ServiceDelete(DeleteView):
    model = Service
    success_url = reverse_lazy('client:index')


# adding service render to pdf
class PrintPdf(View):
    def get(self, request, *args, **kwargs):
        queryset = Service.objects.filter(id=self.kwargs.get('pk')).select_related('client').prefetch_related(
            'client__cardiologist').values().values('id', 'MDC_IDC_MSMT_BATTERY_VOLTAGE', 'MDC_IDC_SESS_TYPE', 'MDC_IDC_SESS_DTM',
                                               'client_id', 'client_id__last_name', 'client_id__first_name',
                                               'client_id__cardiologist__id', 'client_id__cardiologist__first_name',
                                               'client_id__cardiologist__last_name', 'client_id__cardiologist__str_address',
                                               'client_id__cardiologist__st_address', 'client_id__cardiologist__ct_address','client_id__cardiologist__pc_address')[0]
        html_template = render_to_string('clients/pdf/pdf_detail.html', queryset)

        pdf_file = HTML(string=html_template, base_url=request.build_absolute_uri()).write_pdf()
        response = HttpResponse(pdf_file, content_type='application/pdf')
        response['Content-Disposition'] = 'filename="home_page.pdf"'
        return response



# Cardiologist

class CardiologistCreate(CreateView):
    template_name = 'clients/cardiologist/doctor_new.html'
    form_class = CardiologistForm
    success_url = reverse_lazy('client:cardiologist_index')


class CardiologistView(ListView):
    template_name = 'clients/cardiologist/doctor_index.html'
    context_object_name = 'all_cardiologist'
    paginate_by = 10

    def get_queryset(self):
        return Cardiologist.objects.all()


class CardiologistDetailView(DetailView, DeleteView, CreateView):
    model = Cardiologist
    template_name = 'clients/cardiologist/doctor_detail.html'
    success_url = reverse_lazy('client:cardiologist_index')
    #fields= ['record_number','first_name', 'last_name', 'dob', 'device_man', 'device_name', 'implant_date', 'device_serial', 'bol_voltage','eri_voltage']
    form_class = CardiologistForm


class CardiologistDelete(DeleteView):
    model = Cardiologist
    success_url = reverse_lazy('client:cardiologist_index')


class CardiologistUpdate(UpdateView):
    model = Cardiologist
    template_name = 'clients/cardiologist/doctor_detail.html'
    form_class = CardiologistForm


class CardiologistSearchList(ListView):
    template_name = 'clients/cardiologist/doctor_search.html'
    model = Cardiologist
    context_object_name = 'results_list'

    def get_queryset(self):
        search = self.request.GET.get('search')
        queryset = Cardiologist.objects.filter(Q(last_name__icontains=search)|Q(first_name__icontains=search))
        return queryset



# General Paractitioner

class GeneralPractitionerCreate(CreateView):
    model = General_Practitioner
    template_name = 'clients/gp/doctor_new.html'
    form_class = General_PractitionerForm
    success_url = reverse_lazy('client:generalpractitioner_index')


class GeneralPractitionerView(ListView):
    template_name = 'clients/gp/doctor_index.html'
    context_object_name = 'all_GeneralPractitioner'
    paginate_by = 10

    def get_queryset(self):
        return General_Practitioner.objects.all()


class GeneralPractitionerDetailView(DetailView, DeleteView, CreateView):
    model = General_Practitioner
    template_name = 'clients/gp/doctor_detail.html'
    success_url = reverse_lazy('client:generalgractitioner_index')
    form_class = General_PractitionerForm

class GeneralPractitionerUpdate(UpdateView):
    model = General_Practitioner
    template_name = 'clients/gp/doctor_update_form.html'
    form_class = General_PractitionerForm
    #success_url = reverse_lazy('client:generalgractitioner_detail')
    template_name_suffix = '_update_form'


class GeneralPractitionerDelete(DeleteView):
    model = General_Practitioner
    success_url = reverse_lazy('client:generalpractitioner_index')
    success_message = 'Success: Client Deleted.'


class GeneralPractitionerSearchList(ListView):
    template_name = 'clients/gp/doctor_search.html'
    model = General_Practitioner
    context_object_name = 'results_list'

    def get_queryset(self):
        search = self.request.GET.get('search')
        queryset = General_Practitioner.objects.filter(Q(last_name__icontains=search)|Q(first_name__icontains=search))
        return queryset

patientdb/patient/templates/clients/base.html
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Clients</title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {{ form.media }}


</head>
<body>
<div class="container">
    {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <title class="navbar-brand" id="title">Remote Master Command</title>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'client:index' %}">
                        <span class="oi oi-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'client:client_new' %}">
                            <span class="oi oi-person" aria-hidden="true"></span>&nbsp; New Client
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'client:client_index' %}">
                            <span class="oi oi-people" aria-hidden="true"></span>&nbsp; Client Index
                        </a>
                     </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span class="oi oi-account-login" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    </li>
        </div>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'client:search' %}">
                <input class="form-control mr-sm-2" type="search" name="search" placeholder="Client Search" aria-label="Search">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
    {% endblock %}

    {% block content %}
    {% endblock  %}

</div>

</body>
</html>
{% block script %}
<script type="text/javascript">
$(document).ready(function () {
    var links = $('.navbar ul li a');
    $.each(links, function (key, va) {
        if (va.href == document.URL) {
            $(this).addClass('active');
        }
    });
});
</script>
{% endblock %}

patientdb/patient/templates/clients/client_detail.html
{% extends 'clients/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div>
	<h3>Client Details</h3>
  <hr>
  <div>
      <a class="btn btn-secondary" href="{% url 'client:history' client.pk %}">Service History</a>
      <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#updateModal">Update</button>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
    </div>
  <hr>
	<h4>{{client.first_name}} {{client.last_name}}</h4>
	<div class="row">
		<div class="col">
			<label style="color: #7B1FA2; font-weight: bold;">Record Number: </label> {{client.record_number}}
			<br>
			<label style="color: #7B1FA2; font-weight: bold;">First Name: </label> {{client.first_name}}
			<br>
			<label style="color: #7B1FA2; font-weight: bold;">Last Name: </label> {{client.last_name}}
			<br>
			<label style="color: #7B1FA2; font-weight: bold;">Date of Birth: </label> {{client.dob}}
		</div>
		<div class="col">
			<label style="color: #7B1FA2; font-weight: bold;">Device manufacturer: </label> {{client.device}}
			<br>
			<label style="color: #7B1FA2; font-weight: bold;">Device Serial: </label> {{client.device_serial}}
			<br>
			<label style="color: #7B1FA2; font-weight: bold;">Implant Date: </label> {{client.implant_date}}

      </div>
      <div class='col'>
          <label style="color: #7B1FA2; font-weight: bold;">Doctors List: </label>
          <br>
        <ul class="list-group">
          <li class="list-group-item">Cardiologist: {{ client.cardiologist.first_name }} {{ client.cardiologist.last_name }}</li>
          <li class="list-group-item">General Practitioner: {{ client.general_practitioner.first_name }} {{ client.general_practitioner.last_name }}</li>		
        </ul>
      </div>
	<hr>
</div>


<!-- Delete Client Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Delete Client</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete "{{object.first_name}} {{ object.last_name }}"</p>
      </div>
      <div class="modal-footer">
	  	<form method="post" action="{% url 'client:client_delete' client.pk %}">
			{% csrf_token %}
        	<button type="submit" class="btn btn-danger">Delete Client</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</form>
      </div>
    </div>
  </div>
</div>



<!-- Update Client Modal-->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Update Client</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
      <div class="container">
          <nav>
              <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#client_details" role="tab" aria-controls="nav-home" aria-selected="true">Client Details</a>
                <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#device_details" role="tab" aria-controls="nav-profile" aria-selected="false">Device Details</a>
                <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#doctors_list" role="tab" aria-controls="nav-contact" aria-selected="false">Doctors List</a>
              </div>
          </nav>


	  	<form method="post" action="{% url 'client:client_update' client.pk %}">
      {% csrf_token %}
      <div class='tab-content' id="nav-tabContent">
			  <div class='form-row tab-pane fade show active' role="tabpanel" id="client_details">
          <div class="form-row">
            <div class='form-group col-md-4 mb-0'>
              {{ form.record_number|as_crispy_field }}
              {{ form.first_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.dob|as_crispy_field }}
                {{ form.last_name|as_crispy_field }}
            </div>
          </div>
        </div>

        <div class='form-row tab-pane fade' role="tabpanel" id="device_details" role="tabpanel">
          <div class='form-row'>
            <div class='form-group col-md-6 mb-0'>
              {{ form.device|as_crispy_field }}
            </div>
            <div class='form-group col-md-6 mb-0'>
              {{ form.device_serial|as_crispy_field }}
              {{ form.implant_date|as_crispy_field }}
            </div>
          </div>
        </div>

        <div class='form-row tab-pane fade' role="tabpanel" id="doctors_list" role="tabpanel">
          <div class='form-row'>
                <div class='form-group col-md-6 mb-0'>
                    {{ form.general_practitioner|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.cardiologist|as_crispy_field }}
                </div>
          </div>
        </div>

        <button type="submit" class="btn btn-danger">Update Client</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      </form>
      

      </div>
    </div>
    </div>
  </div>
</div>
{% endblock %}

patientdb/patient/templates/clients/client_new.html
{% extends 'clients/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add a Client</h1>
    <form method="POST" class="new-form"  enctype="multipart/form-data">
      {% csrf_token %}
      <div class='form-row'>
        <div class='form-group col-md-4 mb-0'>
          {{ form.record_number|as_crispy_field }}
          {{ form.first_name|as_crispy_field }}
          {{ form.last_name|as_crispy_field }}
          {{ form.dob|as_crispy_field }}
        </div>

        <div class='form-group col-md-4 mb-0'>
            {{ form.device|as_crispy_field }}
            {{ form.implant_date | as_crispy_field }}
            {{ form.general_practitioner|as_crispy_field }}
            
        </div>
        <div class='form-group col-md-4 mb-0'>
            <div >
                {{ form.device_serial|as_crispy_field }}
                {{ form.cardiologist|as_crispy_field }}
            </div>
        </div>

      </div>
      <div class='form-row'>
      <button type="submit" class="btn btn-secondary">Add a client</button>
      </div>
  </form>
{% endblock %}

{% block script %}
<script type="text/javascript">
  $(function () {
    $('#datepicker').datepicker()
  });
</script>
{% endblock %}

patientdb/patient/templates/clients/index.html
{% extends "clients/base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a an area that will show demographics of the site. This will include things as the # of patients an break down in device manufacturers, device types, if the patient is on RHM, hazard alerts, etc..</p>
  <hr class="my-4">
  <p>The breakdown will be in graph and numerical format with no links.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

{% endblock %}